//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annotation
    {
        public int Id { get; set; }
        public byte[] Bg { get; set; }
        public byte[] VectGraphics { get; set; }
        public byte[] Thumb { get; set; }
        public int CanvWidth { get; set; }
        public int CanvHeight { get; set; }
        public string Name { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Discussion Discussion { get; set; }
    }
}
