//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArgPoint
    {
        public ArgPoint()
        {
            this.Comment = new HashSet<Comment>();
            this.Attachment = new HashSet<Attachment>();
        }
    
        public int Id { get; set; }
        public string Point { get; set; }
        public int SideCode { get; set; }
        public bool SharedToPublic { get; set; }
        public string RecentlyEnteredSource { get; set; }
        public string RecentlyEnteredMediaUrl { get; set; }
        public bool ChangesPending { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual Person Person { get; set; }
        public virtual RichText Description { get; set; }
    }
}
