//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscCtx : DbContext
    {
        public DiscCtx(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Person> Person { get; set; }
        public DbSet<Discussion> Discussion { get; set; }
        public DbSet<ArgPoint> ArgPoint { get; set; }
        public DbSet<Topic> Topic { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<Attachment> Attachment { get; set; }
        public DbSet<GeneralSide> GeneralSide { get; set; }
        public DbSet<Source> Source { get; set; }
        public DbSet<RichText> RichText { get; set; }
        public DbSet<Annotation> Annotation { get; set; }
        public DbSet<StatsEvent> StatsEvent { get; set; }
        public DbSet<Session> Session { get; set; }
        public DbSet<Seat> Seat { get; set; }
        public DbSet<MediaData> MediaDataSet { get; set; }
        public DbSet<CommentPersonReadEntry> CommentPersonReadEntry { get; set; }
    }
}
