//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsEvent
    {
        public int Id { get; set; }
        public int Event { get; set; }
        public int DiscussionId { get; set; }
        public string DiscussionName { get; set; }
        public int TopicId { get; set; }
        public string TopicName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime Time { get; set; }
        public int DeviceType { get; set; }
    }
}
