//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.ArgPoint = new HashSet<ArgPoint>();
            this.Person = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Annotation { get; set; }
        public bool Running { get; set; }
        public int CumulativeDuration { get; set; }
    
        public virtual ICollection<ArgPoint> ArgPoint { get; set; }
        public virtual Discussion Discussion { get; set; }
        public virtual ICollection<Person> Person { get; set; }
    }
}
