//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Format { get; set; }
        public string VideoThumbURL { get; set; }
        public string VideoEmbedURL { get; set; }
        public string VideoLinkURL { get; set; }
        public string Link { get; set; }
        public string Title { get; set; }
        public byte[] Thumb { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual ArgPoint ArgPoint { get; set; }
        public virtual Person Person { get; set; }
        public virtual Discussion Discussion { get; set; }
        public virtual Person PersonWithAvatar { get; set; }
        public virtual MediaData MediaData { get; set; }
    }
}
