//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        public Discussion()
        {
            this.Topic = new HashSet<Topic>();
            this.Attachment = new HashSet<Attachment>();
            this.GeneralSide = new HashSet<GeneralSide>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public string HtmlBackground { get; set; }
    
        public virtual ICollection<Topic> Topic { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual ICollection<GeneralSide> GeneralSide { get; set; }
        public virtual RichText Background { get; set; }
    }
}
