//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Topic = new HashSet<Topic>();
            this.ArgPoint = new HashSet<ArgPoint>();
            this.Comment = new HashSet<Comment>();
            this.Attachment = new HashSet<Attachment>();
            this.GeneralSide = new HashSet<GeneralSide>();
            this.Screenshot = new HashSet<Annotation>();
            this.ReadEntry = new HashSet<CommentPersonReadEntry>();
        }
    
        public string Name { get; set; }
        public string Email { get; set; }
        public int Id { get; set; }
        public int Color { get; set; }
        public bool Online { get; set; }
        public Nullable<int> SeatId { get; set; }
        public int OnlineDevType { get; set; }
        public Nullable<int> SessionId { get; set; }
    
        public virtual ICollection<Topic> Topic { get; set; }
        public virtual ICollection<ArgPoint> ArgPoint { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual ICollection<GeneralSide> GeneralSide { get; set; }
        public virtual ICollection<Annotation> Screenshot { get; set; }
        public virtual Attachment AvatarAttachment { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Session Session { get; set; }
        public virtual ICollection<CommentPersonReadEntry> ReadEntry { get; set; }
    }
}
