//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime EstimatedDateTime { get; set; }
        public int EstimatedTimeSlot { get; set; }
        public System.DateTime EstimatedEndDateTime { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
