// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DiscSvc.Reporting
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Discussions.DbModel;
    using Discussions.RTModel.Model;
    using System.Diagnostics;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class Report : ReportBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@" 

<!DOCTYPE HTML>
<html>
    <head>
	    <meta charset='utf-8'> 
        <title>Topic report</title>		
	    <link href=""report.css"" rel=""stylesheet"" type=""text/css"" />
    </head>
	
    <body> 
        
		 <div class=""blueSpan"">

			<h2>Tohoku University</h2>
			<br />
			<br />

			<h1>Discussion System</h1>

			<br />
			<br />

			<h2>Topic Report</h2>
			<br />
			<br />
			<br />
			<br />

			<h3 style=""color:white"">  ");
            
            #line 39 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.Date.ToShortDateString()));
            
            #line default
            #line hidden
            this.Write(@" <h3>
         </div>
		    
	    <!------------------------------------------------------------------------------------->
	    <h3>
			Contents
	    </h3>

		<div class=""toc"">
			<a href=""#basicInfo"">Basic information</a><br>
			<a href=""#participants"">Participants</a><br>
			<a href=""bgpage?id=");
            
            #line 50 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(QueryParams.DiscussionId));
            
            #line default
            #line hidden
            this.Write("\" target=\"_blank\">Background</a><br>\r\n\t\t\t<a href=\"");
            
            #line 51 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MediaUrl));
            
            #line default
            #line hidden
            this.Write("\" target=\"_blank\">Media of discussion background</a><br>\r\n\t\t\t<a href=\"");
            
            #line 52 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SourcesUrl));
            
            #line default
            #line hidden
            this.Write(@""" target=""_blank"">Sources of discussion background</a><br>
			<a href=""#finalBoard"">Final Public Dashboard</a><br>
			<a href=""#summary"">Summary information</a><br>
			<!--<a href=""#argPoints"">Argument points</a><br>-->
			<a href=""#clustInfo"">Cluster information</a><br>
	        <a href=""#unclusteredArgs"">Unclustered arguments</a><br>
    		<a href=""#linkInfo"">Link information</a><br>
		</div>

		<!------------------------------------------------------------------------------------->
		
	    <h3 style=""page-break-before: always;"">
          <a id=""basicInfo"">Basic information</a>
        </h3>
 
		<table>
			<tr>
				<td>Discussion</td>
				<td>");
            
            #line 70 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReportParams.Discussion.Subject));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Topic</td>\r\n\t\t\t\t<td>");
            
            #line 74 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReportParams.Topic.Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Session</td>\r\n\t\t\t\t<td>");
            
            #line 78 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReportParams.Session.Name));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Date and time of discussion</td>\r\n\t\t\t\t<td>");
            
            #line 82 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReportParams.Session.EstimatedDateTime.ToString()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Total time of one topic</td>\r\n\t\t\t\t<td>");
            
            #line 86 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TimeSpan.FromSeconds(ReportParams.Topic.CumulativeDuration).ToString()));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\t\r\n        </table>\r\n\r\n\t\t<!---------------------------------------" +
                    "---------------------------------------------->\r\n\r\n\t\t<h3>\r\n\t\t\t<a id=\"participant" +
                    "s\">Participants</a>\r\n\t\t</h3>\r\n\r\n\t\t<table style=\"width:auto\">\r\n\t\t\t");
            
            #line 97 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
 foreach(var tuple in Participants) 
			   { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t   <tr>\r\n\t\t\t\t\t   ");
            
            #line 100 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

						   EmitColoredUserCell(tuple.Item1);
						   EmitColoredUserCell(tuple.Item2);
					   
            
            #line default
            #line hidden
            this.Write("\t\t\t\t   </tr>\r\n\t\t\t");
            
            #line 105 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</table>\r\n\r\n\t\t<!---------------------------------------------------------------" +
                    "---------------------->\r\n\r\n\t\t<h3>\r\n\t\t\t<a id=\"finalBoard\">Final Public Dashboard<" +
                    "/a>\r\n\t\t</h3>\r\n\t\t\r\n\t\t<div class=\"finalScreenshot\">\r\n\t\t\t<img src=\"");
            
            #line 115 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Screenshots[-1].url));
            
            #line default
            #line hidden
            this.Write(@""" alt=""Final public dashboard"" style=""width:100%;"">
		</div>

		<!------------------------------------------------------------------------------------->

		<h3>
			<a id=""summary"" style=""page-break-before: always;"">Summary information</a>
		</h3>

		<table>
			<tr>
			   <td>Arg.points</td>
			   <td>");
            
            #line 127 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ComplexReport.TotalArgPointReport.numPoints));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t   <td>Attachments</td>\r\n\t\t\t   <td>");
            
            #line 131 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ComplexReport.TotalArgPointReport.numMediaAttachments));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t   <td>Sources (total events) </td>\r\n\t\t\t   <td>");
            
            #line 135 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ComplexReport.EventTotals.TotalSourceAdded));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t   <td>Clusters</td>\r\n\t\t\t   <td>");
            
            #line 139 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ComplexReport.ClusterReports.Count));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t   <td>Links</td>\r\n\t\t\t   <td>");
            
            #line 143 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ComplexReport.LinkReports.Count));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t   <td>Comments</td>\r\n\t\t\t   <td>");
            
            #line 147 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ComplexReport.TotalArgPointReport.numComments));
            
            #line default
            #line hidden
            this.Write("</td> \r\n\t\t\t</tr>\r\n\t\t</table>\r\n\r\n\t\t <!--------------------------------------------" +
                    "----------------------------------------->\r\n\r\n\t \t <h3 style=\"page-break-before: " +
                    "always;\">\r\n\t\t\t<a id=\"clustInfo\">Cluster information</a>\r\n\t\t </h3>\r\n\t\t\r\n\t\t ");
            
            #line 157 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
ClusterInformation(ComplexReport);
            
            #line default
            #line hidden
            this.Write("\r\n\t\t <!--------------------------------------------------------------------------" +
                    "----------->\r\n\r\n\t\t <h3 style=\"page-break-before: always;\">\r\n\t\t\t<a id=\"unclustere" +
                    "dArgs\">Unclustered arguments</a>\r\n\t     </h3>\r\n\t\t ");
            
            #line 164 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

		    var argPointsOf = ReportParams.Topic.ArgPoint.OrderBy(ap1=>ap1.OrderNumber);
			if (argPointsOf.Count() > 0)
			{ 
            
            #line default
            #line hidden
            this.Write("\t\t\t   <table>\r\n\t\t\t     <tbody>\r\n\t\t\t     ");
            
            #line 170 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

				foreach (var ap in argPointsOf)
				{
					if (ap.SharedToPublic && !ProcessedArgPoints.Contains(ap.Id))
						ArgPointNode(ap);                      
				}
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\r\n                </tbody>\r\n\t\t\t  </table>\r\n\t\t\t   ");
            
            #line 179 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

			}
			else
			{
				
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<No unclustered arguments> \r\n\t\t\t\t");
            
            #line 185 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

			}		 
		 
            
            #line default
            #line hidden
            this.Write("\t\t <!----------------------------------------------------------------------------" +
                    "--------->\r\n\r\n\t \t <h3>\t\t\t\r\n\t\t\t<a id=\"linkInfo\">Link information</a>\r\n\t\t </h3>\r\n\t" +
                    "\t\r\n\t\t ");
            
            #line 194 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
LinkInformation(ComplexReport);
            
            #line default
            #line hidden
            this.Write(@"
	    <form name=""emailForm"" method=""post"" action=""/discsvc/email"">
        <p>
            <b>Enter email</b>
			<br/>
            <input type=""email"" name=""email"" id=""email"" size=""40""/>
            <input type=""hidden"" name=""reportUrl"" id=""reportUrl"" value=""");
            
            #line 201 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReportUrl));
            
            #line default
            #line hidden
            this.Write("\"/>\r\n        </p>      \r\n        <p>\r\n            <input class=\"siteBtn1\" type=\"s" +
                    "ubmit\" value=\"Send\"/>\r\n        </p>\r\n    </form>\r\n    </body>\r\n</html>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 210 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
 
	void EmitColoredUserCell(Person p)
	{
		if(p==null)
		{
			
        
        #line default
        #line hidden
        
        #line 215 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t\t<td></td>\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 217 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

			return;
		}
		
        
        #line default
        #line hidden
        
        #line 220 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t<td style=\"padding:15px; border-left:solid 50px ");

        
        #line default
        #line hidden
        
        #line 221 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.IntToHtml(p.Color)));

        
        #line default
        #line hidden
        
        #line 221 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\">");

        
        #line default
        #line hidden
        
        #line 221 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 221 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("</td>\t\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 222 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

	}

	void EmitMediaCell(Attachment a, int i)
	{
		if(a==null)
			return;

		
        
        #line default
        #line hidden
        
        #line 230 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t<div style=\"padding-top:40px\">\r\n\t\t\t<p> ");

        
        #line default
        #line hidden
        
        #line 232 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(i));

        
        #line default
        #line hidden
        
        #line 232 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(". ");

        
        #line default
        #line hidden
        
        #line 232 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(a.Link));

        
        #line default
        #line hidden
        
        #line 232 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("</p>\r\n\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 234 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetPastableHtml(a, BaseUrl)));

        
        #line default
        #line hidden
        
        #line 234 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\r\n\t\t</div> \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 236 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

	}
 
	void EmitMediaTable(IEnumerable<Attachment> media)
	{
		
        
        #line default
        #line hidden
        
        #line 241 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t    <div style=\"text-align: center\">\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 243 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
   var i = 1;
		          foreach(var m in media.OrderBy(m=>m.OrderNumber))
					 EmitMediaCell(m, i++);
			
        
        #line default
        #line hidden
        
        #line 246 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(" \r\n\t\t</div>\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 248 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

	}

	void EmitSourceCell(Source s, int i)
    {
		if(s==null)
			return;

		
        
        #line default
        #line hidden
        
        #line 256 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t<div style=\"padding-top:40px\">\r\n\t\t   ");

        
        #line default
        #line hidden
        
        #line 258 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(i));

        
        #line default
        #line hidden
        
        #line 258 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(". <a href=\"");

        
        #line default
        #line hidden
        
        #line 258 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(s.Text));

        
        #line default
        #line hidden
        
        #line 258 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\">");

        
        #line default
        #line hidden
        
        #line 258 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(s.Text));

        
        #line default
        #line hidden
        
        #line 258 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("</a>\r\n\t\t</div> \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 260 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

    }

	void EmitCommentOrArgPointLine(Person p, string Text, DiscLink link)
    {
		
        
        #line default
        #line hidden
        
        #line 265 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t<tr>\r\n\t\t\t<td style=\"padding:15px; border:0px; border-left:solid 20px ");

        
        #line default
        #line hidden
        
        #line 267 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.IntToHtml(p.Color)));

        
        #line default
        #line hidden
        
        #line 267 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\">");

        
        #line default
        #line hidden
        
        #line 267 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));

        
        #line default
        #line hidden
        
        #line 267 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("</td>\r\n\t\t\t<td style=\"border:0px\">");

        
        #line default
        #line hidden
        
        #line 268 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(link.Emit(Text)));

        
        #line default
        #line hidden
        
        #line 268 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("</td>\r\n\t\t</tr>\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 270 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

    }

	void ArgPointNode(ArgPoint ap)
    {
		if(ap==null)
			return;
		if(ap.Person==null)
			return;	

		
        
        #line default
        #line hidden
        
        #line 280 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t<tr>\r\n\t\t\t<td style=\"padding:25px 0; border:0px; border-left:solid 20px; border-" +
        "left-color:");

        
        #line default
        #line hidden
        
        #line 282 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.IntToHtml(ap.Person.Color)));

        
        #line default
        #line hidden
        
        #line 282 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\">\r\n\t\t\t\t<div class=\"boldCaption\">");

        
        #line default
        #line hidden
        
        #line 283 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((new DiscLink{Id=ap.Id, LinkObject=LinkObject.ArgPoint, EmitType=EmitType.Anchor}).Emit("Point#" + ap.OrderNumber + ". " + ap.Point)));

        
        #line default
        #line hidden
        
        #line 283 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("</div> \r\n\t\t\t\r\n\t\t\t\t<div style=\"text-align: center; padding-top:40px\">\r\n\t\t\t\t    <im" +
        "g src=");

        
        #line default
        #line hidden
        
        #line 286 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Screenshots[-ap.Id-1].url));

        
        #line default
        #line hidden
        
        #line 286 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(" > \t\t\r\n\t\t\t    </div>\r\n\r\n\t\t\t\t<p>\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 290 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.processLineBreaks(ap.Description.Text)));

        
        #line default
        #line hidden
        
        #line 290 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(" \r\n\t\t\t\t</p>\r\n\t\r\n\t\t\t\t<!-- media -->\r\n\t\t\t\t<div class=\"boldCaption\">Media</div> \r\n\t\t" +
        "\t\t");

        
        #line default
        #line hidden
        
        #line 295 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
						
				EmitMediaTable(ap.Attachment);
				
        
        #line default
        #line hidden
        
        #line 297 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t\r\n\t\t\t\t<div class=\"boldCaption\">Sources</div> \r\n\t\t\t\t<div style=\"text-align: lef" +
        "t; padding-left:40px\">\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 301 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
 var i = 1;
						foreach(var src in ap.Description.Source.OrderBy(s=>s.OrderNumber)) 
						{ 
        
        #line default
        #line hidden
        
        #line 303 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t\t\t\t   ");

        
        #line default
        #line hidden
        
        #line 304 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(i++));

        
        #line default
        #line hidden
        
        #line 304 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(". <a href=\"");

        
        #line default
        #line hidden
        
        #line 304 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(src.Text));

        
        #line default
        #line hidden
        
        #line 304 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\">");

        
        #line default
        #line hidden
        
        #line 304 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(src.Text));

        
        #line default
        #line hidden
        
        #line 304 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("<a><br>\t\t\t\t\t   \r\n\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 305 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
 } 
        
        #line default
        #line hidden
        
        #line 305 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t\t</div>\r\n\r\n\t\t\t\t<!-- comments -->\r\n\t\t\t\t<div class=\"boldCaption\">Comments</div> " +
        "\r\n\t\t\t\t<table>\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 311 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

				foreach(var c in ap.Comment) 
				{
					if(c.Person==null)
						continue;
					EmitCommentOrArgPointLine(c.Person, c.Text, new DiscLink{Id=c.Id, LinkObject=LinkObject.Comment, EmitType=EmitType.Anchor});
				}
        
        #line default
        #line hidden
        
        #line 317 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t\t</table>\r\n\t\t\t</td>\r\n\t    </tr>\r\n\t\t");

        
        #line default
        #line hidden
        
        #line 321 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
	
    }

	void ClusterTableLine(string clustTitle, int clustId)
    {
        
        #line default
        #line hidden
        
        #line 325 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t");

        
        #line default
        #line hidden
        
        #line 326 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture((new DiscLink{Id=clustId, LinkObject=LinkObject.Cluster, EmitType=EmitType.Anchor}).Emit(strClusterTableLine(clustTitle,clustId))));

        
        #line default
        #line hidden
        
        #line 326 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\r\n    ");

        
        #line default
        #line hidden
        
        #line 327 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
}

	string strClusterTableLine(string clustTitle, int clustId)
    {
		if (string.IsNullOrEmpty(clustTitle))
		{   
			return string.Format("Cluster_{0}", clustId);
		}
		else
		{
			return string.Format("Cluster \"{0}\"", clustTitle); 
		}
    }

	private void ClusterTable(Reporter.ClusterReport clustReport, string image)
    {
		
        
        #line default
        #line hidden
        
        #line 343 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t<div class=\"cluster\" style=\"page-break-after: always; border-left-color:");

        
        #line default
        #line hidden
        
        #line 344 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.IntToHtml(clustReport.initialOwner.Color)));

        
        #line default
        #line hidden
        
        #line 344 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\">\r\n\t\t\t<div class=\"boldCaption\">\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 346 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
 ClusterTableLine(clustReport.clusterTitle, clustReport.clusterId); 
        
        #line default
        #line hidden
        
        #line 346 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\r\n\t\t\t</div>\r\n\t\t\r\n\t\t\t<div style=\"text-align: center; padding-top:40px\">\r\n\t\t\t\t<img" +
        " src=");

        
        #line default
        #line hidden
        
        #line 350 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(image));

        
        #line default
        #line hidden
        
        #line 350 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(" style=\"max-width:1024px\"> \t\t\r\n\t\t\t</div>\r\n\r\n\t\t\t<table>\r\n\t\t\t <tbody>\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 355 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

				foreach (var point in clustReport.points)
				{
					if(point.Person!=null && point.Topic != null && point.SharedToPublic)
					{
						ArgPointNode(point);  
						ProcessedArgPoints.Add(point.Id);
						//EmitCommentOrArgPointLine(point.Person,  "Point# " + point.OrderNumber + ". " + point.Point, 
						//				          new DiscLink{Id=point.Id, LinkObject=LinkObject.ArgPoint, EmitType=EmitType.Ref});			
					}
				};
				
        
        #line default
        #line hidden
        
        #line 366 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t    \t</tbody>\r\n\t\t\t</table>\r\n\t\t</div> \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 370 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

    }

	void ClusterInformation(Reporter.ReportCollector hardReport)
    {
        if (hardReport.ClusterReports.Count > 0)
        {
            foreach (var clusterReport in hardReport.ClusterReports)            
                ClusterTable(clusterReport, Screenshots[clusterReport.clusterShId].url);                           
        }
        else
        {
			
        
        #line default
        #line hidden
        
        #line 382 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("             {No clusters}\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 384 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

        }
    }

	private void LinkTable(Reporter.ReportCollector hardReport, LinkReportResponse link, string image)
    {
		
        
        #line default
        #line hidden
        
        #line 390 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\r\n\t\t<div class=\"link\" style=\"border-left-color:");

        
        #line default
        #line hidden
        
        #line 392 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.IntToHtml(link.initOwner.Color)));

        
        #line default
        #line hidden
        
        #line 392 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\">\r\n\t\t\t<div class=\"boldCaption\">\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 394 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

				if (string.IsNullOrEmpty(link.Caption))
				{   
        
        #line default
        #line hidden
        
        #line 396 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t\t\tLink\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 398 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
}
				else
				{
        
        #line default
        #line hidden
        
        #line 400 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 401 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("Link \"{0}\"", link.Caption)));

        
        #line default
        #line hidden
        
        #line 401 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write(" \r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 402 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
}
        
        #line default
        #line hidden
        
        #line 402 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t</div>\r\n\t\t\r\n\t\t\t<table>\r\n\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 406 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"


			    if (link.EndpointArgPoint1)
					EmitCommentOrArgPointLine(link.ArgPoint1.Person, Helpers.ArgPointToStr(link.ArgPoint1), 
											 new DiscLink{Id=link.ArgPoint1.Id, LinkObject=LinkObject.ArgPoint, EmitType=EmitType.Ref});			
				else
                {
					var idOfCluster = link.IdOfCluster1;
					var cluster = hardReport.ClusterReports.Single(c=>c.clusterId==idOfCluster);
					EmitCommentOrArgPointLine(cluster.initialOwner, strClusterTableLine(link.ClusterCaption1, link.IdOfCluster1), 
												new DiscLink{Id=link.IdOfCluster1, LinkObject=LinkObject.Cluster, EmitType=EmitType.Ref});
                }
				
			    if (link.EndpointArgPoint2)
					EmitCommentOrArgPointLine(link.ArgPoint2.Person, Helpers.ArgPointToStr(link.ArgPoint2),
										     new DiscLink{Id=link.ArgPoint2.Id, LinkObject=LinkObject.ArgPoint, EmitType=EmitType.Ref});			
				else
                {
					var idOfCluster = link.IdOfCluster2;
					var cluster = hardReport.ClusterReports.Single(c=>c.clusterId==idOfCluster);
					EmitCommentOrArgPointLine(cluster.initialOwner, strClusterTableLine(link.ClusterCaption2, link.IdOfCluster2),
											 new DiscLink{Id=link.IdOfCluster2, LinkObject=LinkObject.Cluster, EmitType=EmitType.Ref});				
                }
				
        
        #line default
        #line hidden
        
        #line 429 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("\t\t\t</table>\r\n\t\t</div> \r\n\t\t");

        
        #line default
        #line hidden
        
        #line 432 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

    }

	void LinkInformation(Reporter.ReportCollector hardReport)
    {
        if (hardReport.LinkReports.Count > 0)
        {
            foreach (var linkReport in hardReport.LinkReports)            
                LinkTable(hardReport, linkReport, Screenshots[linkReport.linkShId].url);                           
        }
        else
        {
			
        
        #line default
        #line hidden
        
        #line 444 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"
this.Write("             {No links}\r\n\t\t\t");

        
        #line default
        #line hidden
        
        #line 446 "C:\projects\TDS\discussions\DiscSvc\Reporting\Report.tt"

        }
    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class ReportBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
