using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Discussions.RTModel
{
    //for normal shapes, Ids are generated locally on clients
    //for badges, they are generated by this class
    public class BadgeShapeIdGenerator
    {
        private int _next;

        public BadgeShapeIdGenerator()
        {
            _next = int.MaxValue;
        }

        public BadgeShapeIdGenerator(int next)
        {
            _next = next;
        }

        public int NextId()
        {
            return _next--;
        }

        public int CurrentId()
        {
            return _next;
        }
    }
}