//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussions.TdsSvcRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SArgPoint", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SArgPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumUnreadCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecentlyEnteredMediaUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecentlyEnteredSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SharedToPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SideCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumUnreadComments {
            get {
                return this.NumUnreadCommentsField;
            }
            set {
                if ((this.NumUnreadCommentsField.Equals(value) != true)) {
                    this.NumUnreadCommentsField = value;
                    this.RaisePropertyChanged("NumUnreadComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((this.OrderNumberField.Equals(value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Point {
            get {
                return this.PointField;
            }
            set {
                if ((object.ReferenceEquals(this.PointField, value) != true)) {
                    this.PointField = value;
                    this.RaisePropertyChanged("Point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecentlyEnteredMediaUrl {
            get {
                return this.RecentlyEnteredMediaUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.RecentlyEnteredMediaUrlField, value) != true)) {
                    this.RecentlyEnteredMediaUrlField = value;
                    this.RaisePropertyChanged("RecentlyEnteredMediaUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecentlyEnteredSource {
            get {
                return this.RecentlyEnteredSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.RecentlyEnteredSourceField, value) != true)) {
                    this.RecentlyEnteredSourceField = value;
                    this.RaisePropertyChanged("RecentlyEnteredSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SharedToPublic {
            get {
                return this.SharedToPublicField;
            }
            set {
                if ((this.SharedToPublicField.Equals(value) != true)) {
                    this.SharedToPublicField = value;
                    this.RaisePropertyChanged("SharedToPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SideCode {
            get {
                return this.SideCodeField;
            }
            set {
                if ((this.SideCodeField.Equals(value) != true)) {
                    this.SideCodeField = value;
                    this.RaisePropertyChanged("SideCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SComment", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SComment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArgPointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArgPointId {
            get {
                return this.ArgPointIdField;
            }
            set {
                if ((this.ArgPointIdField.Equals(value) != true)) {
                    this.ArgPointIdField = value;
                    this.RaisePropertyChanged("ArgPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SNewCommentsFrom", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SNewCommentsFrom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumNewCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumNewComments {
            get {
                return this.NumNewCommentsField;
            }
            set {
                if ((this.NumNewCommentsField.Equals(value) != true)) {
                    this.NumNewCommentsField = value;
                    this.RaisePropertyChanged("NumNewComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName {
            get {
                return this.PersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonNameField, value) != true)) {
                    this.PersonNameField = value;
                    this.RaisePropertyChanged("PersonName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCommentReadInfo", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SCommentReadInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Discussions.TdsSvcRef.SComment CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EveryoneInTopicReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Discussions.TdsSvcRef.SPerson[] PersonsWhoReadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Discussions.TdsSvcRef.SComment Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EveryoneInTopicRead {
            get {
                return this.EveryoneInTopicReadField;
            }
            set {
                if ((this.EveryoneInTopicReadField.Equals(value) != true)) {
                    this.EveryoneInTopicReadField = value;
                    this.RaisePropertyChanged("EveryoneInTopicRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Discussions.TdsSvcRef.SPerson[] PersonsWhoRead {
            get {
                return this.PersonsWhoReadField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonsWhoReadField, value) != true)) {
                    this.PersonsWhoReadField = value;
                    this.RaisePropertyChanged("PersonsWhoRead");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SPerson", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SPerson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AvatarAttachmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OnlineDevTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SeatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AvatarAttachmentId {
            get {
                return this.AvatarAttachmentIdField;
            }
            set {
                if ((this.AvatarAttachmentIdField.Equals(value) != true)) {
                    this.AvatarAttachmentIdField = value;
                    this.RaisePropertyChanged("AvatarAttachmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Color {
            get {
                return this.ColorField;
            }
            set {
                if ((this.ColorField.Equals(value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Online {
            get {
                return this.OnlineField;
            }
            set {
                if ((this.OnlineField.Equals(value) != true)) {
                    this.OnlineField = value;
                    this.RaisePropertyChanged("Online");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OnlineDevType {
            get {
                return this.OnlineDevTypeField;
            }
            set {
                if ((this.OnlineDevTypeField.Equals(value) != true)) {
                    this.OnlineDevTypeField = value;
                    this.RaisePropertyChanged("OnlineDevType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SeatId {
            get {
                return this.SeatIdField;
            }
            set {
                if ((this.SeatIdField.Equals(value) != true)) {
                    this.SeatIdField = value;
                    this.RaisePropertyChanged("SeatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSource", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SSource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((this.OrderNumberField.Equals(value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SOrderInfo", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SOrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((this.OrderNumberField.Equals(value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SInAttachment", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SInAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MediaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ThumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoEmbedURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoLinkURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoThumbURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Format {
            get {
                return this.FormatField;
            }
            set {
                if ((this.FormatField.Equals(value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MediaData {
            get {
                return this.MediaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaDataField, value) != true)) {
                    this.MediaDataField = value;
                    this.RaisePropertyChanged("MediaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Thumb {
            get {
                return this.ThumbField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbField, value) != true)) {
                    this.ThumbField = value;
                    this.RaisePropertyChanged("Thumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoEmbedURL {
            get {
                return this.VideoEmbedURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoEmbedURLField, value) != true)) {
                    this.VideoEmbedURLField = value;
                    this.RaisePropertyChanged("VideoEmbedURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoLinkURL {
            get {
                return this.VideoLinkURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoLinkURLField, value) != true)) {
                    this.VideoLinkURLField = value;
                    this.RaisePropertyChanged("VideoLinkURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoThumbURL {
            get {
                return this.VideoThumbURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoThumbURLField, value) != true)) {
                    this.VideoThumbURLField = value;
                    this.RaisePropertyChanged("VideoThumbURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SOutAttachment", Namespace="http://schemas.datacontract.org/2004/07/TdsSvc.Model")]
    [System.SerializableAttribute()]
    public partial class SOutAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ArgPointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiscussionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MediaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MediaDataIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PersonWithAvatarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ThumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoEmbedURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoLinkURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoThumbURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ArgPointId {
            get {
                return this.ArgPointIdField;
            }
            set {
                if ((this.ArgPointIdField.Equals(value) != true)) {
                    this.ArgPointIdField = value;
                    this.RaisePropertyChanged("ArgPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiscussionId {
            get {
                return this.DiscussionIdField;
            }
            set {
                if ((this.DiscussionIdField.Equals(value) != true)) {
                    this.DiscussionIdField = value;
                    this.RaisePropertyChanged("DiscussionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Format {
            get {
                return this.FormatField;
            }
            set {
                if ((this.FormatField.Equals(value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MediaData {
            get {
                return this.MediaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaDataField, value) != true)) {
                    this.MediaDataField = value;
                    this.RaisePropertyChanged("MediaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MediaDataId {
            get {
                return this.MediaDataIdField;
            }
            set {
                if ((this.MediaDataIdField.Equals(value) != true)) {
                    this.MediaDataIdField = value;
                    this.RaisePropertyChanged("MediaDataId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((this.OrderNumberField.Equals(value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersonWithAvatarId {
            get {
                return this.PersonWithAvatarIdField;
            }
            set {
                if ((this.PersonWithAvatarIdField.Equals(value) != true)) {
                    this.PersonWithAvatarIdField = value;
                    this.RaisePropertyChanged("PersonWithAvatarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Thumb {
            get {
                return this.ThumbField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbField, value) != true)) {
                    this.ThumbField = value;
                    this.RaisePropertyChanged("Thumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoEmbedURL {
            get {
                return this.VideoEmbedURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoEmbedURLField, value) != true)) {
                    this.VideoEmbedURLField = value;
                    this.RaisePropertyChanged("VideoEmbedURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoLinkURL {
            get {
                return this.VideoLinkURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoLinkURLField, value) != true)) {
                    this.VideoLinkURLField = value;
                    this.RaisePropertyChanged("VideoLinkURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoThumbURL {
            get {
                return this.VideoThumbURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoThumbURLField, value) != true)) {
                    this.VideoThumbURLField = value;
                    this.RaisePropertyChanged("VideoThumbURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TdsSvcRef.ITdsService")]
    public interface ITdsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetArgPoint", ReplyAction="http://tempuri.org/ITdsService/GetArgPointResponse")]
        Discussions.TdsSvcRef.SArgPoint GetArgPoint(int pointId, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetArgPointsInTopic", ReplyAction="http://tempuri.org/ITdsService/GetArgPointsInTopicResponse")]
        Discussions.TdsSvcRef.SArgPoint[] GetArgPointsInTopic(int topicId, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/AddComment", ReplyAction="http://tempuri.org/ITdsService/AddCommentResponse")]
        void AddComment(Discussions.TdsSvcRef.SComment comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/ChangeCommentText", ReplyAction="http://tempuri.org/ITdsService/ChangeCommentTextResponse")]
        void ChangeCommentText(int commentId, string newText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/RemoveComment", ReplyAction="http://tempuri.org/ITdsService/RemoveCommentResponse")]
        void RemoveComment(int commentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/NumCommentsUnreadBy", ReplyAction="http://tempuri.org/ITdsService/NumCommentsUnreadByResponse")]
        Discussions.TdsSvcRef.SNewCommentsFrom[] NumCommentsUnreadBy(int pointId, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/SubsetOfPersonsWithDots", ReplyAction="http://tempuri.org/ITdsService/SubsetOfPersonsWithDotsResponse")]
        int[] SubsetOfPersonsWithDots(int[] personIds, int topicId, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetCommentsInArgPoint", ReplyAction="http://tempuri.org/ITdsService/GetCommentsInArgPointResponse")]
        Discussions.TdsSvcRef.SComment[] GetCommentsInArgPoint(int pointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetCommentReadInfo", ReplyAction="http://tempuri.org/ITdsService/GetCommentReadInfoResponse")]
        Discussions.TdsSvcRef.SCommentReadInfo GetCommentReadInfo(int commentId, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetSourcesInArgPoint", ReplyAction="http://tempuri.org/ITdsService/GetSourcesInArgPointResponse")]
        Discussions.TdsSvcRef.SSource[] GetSourcesInArgPoint(int pointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/AddSourceArgPoint", ReplyAction="http://tempuri.org/ITdsService/AddSourceArgPointResponse")]
        void AddSourceArgPoint(int pointId, string text, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/MoveSourceUp", ReplyAction="http://tempuri.org/ITdsService/MoveSourceUpResponse")]
        bool MoveSourceUp(int sourceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/MoveSourceDown", ReplyAction="http://tempuri.org/ITdsService/MoveSourceDownResponse")]
        bool MoveSourceDown(int sourceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetSourcesOrder", ReplyAction="http://tempuri.org/ITdsService/GetSourcesOrderResponse")]
        Discussions.TdsSvcRef.SOrderInfo[] GetSourcesOrder(int pointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/AddAttachmentToPoint", ReplyAction="http://tempuri.org/ITdsService/AddAttachmentToPointResponse")]
        void AddAttachmentToPoint(int pointId, Discussions.TdsSvcRef.SInAttachment attachment, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/AddAttachmentToDiscussion", ReplyAction="http://tempuri.org/ITdsService/AddAttachmentToDiscussionResponse")]
        void AddAttachmentToDiscussion(int discussionId, Discussions.TdsSvcRef.SInAttachment attachment, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/AddAttachmentToOwnAvatar", ReplyAction="http://tempuri.org/ITdsService/AddAttachmentToOwnAvatarResponse")]
        void AddAttachmentToOwnAvatar(Discussions.TdsSvcRef.SInAttachment attachment, int callerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/RemoveAttachment", ReplyAction="http://tempuri.org/ITdsService/RemoveAttachmentResponse")]
        void RemoveAttachment(int attachmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/MoveAttachmentUp", ReplyAction="http://tempuri.org/ITdsService/MoveAttachmentUpResponse")]
        bool MoveAttachmentUp(int attachmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/MoveAttachmentDown", ReplyAction="http://tempuri.org/ITdsService/MoveAttachmentDownResponse")]
        bool MoveAttachmentDown(int attachmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetAttachmentsOrder", ReplyAction="http://tempuri.org/ITdsService/GetAttachmentsOrderResponse")]
        Discussions.TdsSvcRef.SOrderInfo[] GetAttachmentsOrder(int pointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITdsService/GetAttachmentsInArgPoint", ReplyAction="http://tempuri.org/ITdsService/GetAttachmentsInArgPointResponse")]
        Discussions.TdsSvcRef.SOutAttachment[] GetAttachmentsInArgPoint(int pointId, bool includeMediaData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITdsServiceChannel : Discussions.TdsSvcRef.ITdsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TdsServiceClient : System.ServiceModel.ClientBase<Discussions.TdsSvcRef.ITdsService>, Discussions.TdsSvcRef.ITdsService {
        
        public TdsServiceClient() {
        }
        
        public TdsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TdsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TdsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Discussions.TdsSvcRef.SArgPoint GetArgPoint(int pointId, int callerId) {
            return base.Channel.GetArgPoint(pointId, callerId);
        }
        
        public Discussions.TdsSvcRef.SArgPoint[] GetArgPointsInTopic(int topicId, int callerId) {
            return base.Channel.GetArgPointsInTopic(topicId, callerId);
        }
        
        public void AddComment(Discussions.TdsSvcRef.SComment comment) {
            base.Channel.AddComment(comment);
        }
        
        public void ChangeCommentText(int commentId, string newText) {
            base.Channel.ChangeCommentText(commentId, newText);
        }
        
        public void RemoveComment(int commentId) {
            base.Channel.RemoveComment(commentId);
        }
        
        public Discussions.TdsSvcRef.SNewCommentsFrom[] NumCommentsUnreadBy(int pointId, int callerId) {
            return base.Channel.NumCommentsUnreadBy(pointId, callerId);
        }
        
        public int[] SubsetOfPersonsWithDots(int[] personIds, int topicId, int callerId) {
            return base.Channel.SubsetOfPersonsWithDots(personIds, topicId, callerId);
        }
        
        public Discussions.TdsSvcRef.SComment[] GetCommentsInArgPoint(int pointId) {
            return base.Channel.GetCommentsInArgPoint(pointId);
        }
        
        public Discussions.TdsSvcRef.SCommentReadInfo GetCommentReadInfo(int commentId, int callerId) {
            return base.Channel.GetCommentReadInfo(commentId, callerId);
        }
        
        public Discussions.TdsSvcRef.SSource[] GetSourcesInArgPoint(int pointId) {
            return base.Channel.GetSourcesInArgPoint(pointId);
        }
        
        public void AddSourceArgPoint(int pointId, string text, int callerId) {
            base.Channel.AddSourceArgPoint(pointId, text, callerId);
        }
        
        public bool MoveSourceUp(int sourceId) {
            return base.Channel.MoveSourceUp(sourceId);
        }
        
        public bool MoveSourceDown(int sourceId) {
            return base.Channel.MoveSourceDown(sourceId);
        }
        
        public Discussions.TdsSvcRef.SOrderInfo[] GetSourcesOrder(int pointId) {
            return base.Channel.GetSourcesOrder(pointId);
        }
        
        public void AddAttachmentToPoint(int pointId, Discussions.TdsSvcRef.SInAttachment attachment, int callerId) {
            base.Channel.AddAttachmentToPoint(pointId, attachment, callerId);
        }
        
        public void AddAttachmentToDiscussion(int discussionId, Discussions.TdsSvcRef.SInAttachment attachment, int callerId) {
            base.Channel.AddAttachmentToDiscussion(discussionId, attachment, callerId);
        }
        
        public void AddAttachmentToOwnAvatar(Discussions.TdsSvcRef.SInAttachment attachment, int callerId) {
            base.Channel.AddAttachmentToOwnAvatar(attachment, callerId);
        }
        
        public void RemoveAttachment(int attachmentId) {
            base.Channel.RemoveAttachment(attachmentId);
        }
        
        public bool MoveAttachmentUp(int attachmentId) {
            return base.Channel.MoveAttachmentUp(attachmentId);
        }
        
        public bool MoveAttachmentDown(int attachmentId) {
            return base.Channel.MoveAttachmentDown(attachmentId);
        }
        
        public Discussions.TdsSvcRef.SOrderInfo[] GetAttachmentsOrder(int pointId) {
            return base.Channel.GetAttachmentsOrder(pointId);
        }
        
        public Discussions.TdsSvcRef.SOutAttachment[] GetAttachmentsInArgPoint(int pointId, bool includeMediaData) {
            return base.Channel.GetAttachmentsInArgPoint(pointId, includeMediaData);
        }
    }
}
